export { default as info1 } from "../assets/images/info1.png";
export { default as info2 } from "../assets/images/info2.png";
export { default as info3 } from "../assets/images/info3.png";
export { default as about } from "../assets/images/about.png";
export { default as about2 } from "../assets/images/about2.png";
export { default as dropdown } from "../assets/images/dropdown.png";
export { default as dropdown2 } from "../assets/images/dropdown2.png";
export { default as cancel } from "../assets/images/cancel.png";
export { default as location } from "../assets/images/location.png";
export { default as arrowright } from "../assets/images/arrow-square-right.svg";
export { default as arrowleft } from "../assets/images/arrow-square-left.svg";
export { default as home } from "../assets/images/home.png";
export { default as tickcircle} from "../assets/images/tick-circle.png";
export { default as spinner} from "../assets/images/spinner.svg";
export { default as profile} from "../assets/images/profile.png";
export { default as filter} from "../assets/images/filter.png";
export { default as star} from "../assets/images/stars.png";
export { default as cash} from "../assets/images/cash.png";
export { default as lock} from "../assets/images/lock.png";
export { default as humidifier} from "../assets/images/humidifier.png";
export { default as love} from "../assets/images/love.png";
export { default as estate} from "../assets/images/estate.png";
export { default as bed} from "../assets/images/bed.png";
export { default as locate} from "../assets/images/locate.png";
export { default as expand} from "../assets/images/expand.png";
export { default as price} from "../assets/images/price.png";
export { default as dashboardIcon} from "../assets/images/dashboardIcon.png";
export { default as logoutIcon} from "../assets/images/logoutIcon.png";
export { default as favoriteIcon} from "../assets/images/favoriteIcon.png";
export { default as listIcon} from "../assets/images/listIcon.png";
export { default as uploadIcon} from "../assets/images/uploadIcon.png";
export { default as userIcon} from "../assets/images/userIcon.png";