export const featuredProperties = [
  {
    id: 0,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
  {
    id: 1,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
  {
    id: 0,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
];

export const popularProperties = [
  {
    id: 0,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
  {
    id: 1,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
  {
    id: 0,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
];

export const newProperties = [
  {
    id: 0,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
  {
    id: 1,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
  {
    id: 0,
    image: "",
    purpose: "for sale",
    price: "200,000",
    title: "2 bedroom flat",
    location: "maitama abuja",
    room: "2 bedroom",
    bathroom: "1 bathroom",
    toilet: "1 toilet",
    kitchen: "1 kitchen",
    square: "2,876 sq",
    parking: "1 parking space",
  },
];
